### ISSUE TITLE
"Resource not exist!" when using default language

### ISSUE THREAD

**Issue by vitosaver** [LazZiya/XLocalizer.DB#3]
Hi Ziya,

Thank you for your great work so far I've been using your library and I have been enjoying it.

I am using version 1.0.0 on both XLocalizer and XLocalizer.DB

When I am on default language in the console I get errors like this:

Log Message:
`"XLocalizer.DB.EF.EFDbResourceProvider: Warning: Resource not exist! Culture: 'hr', Key: 'O nama'"`

Razor code:
`<h3 class="widget-title text-light" localize-content>O nama</h3>`

Configuration:
`.AddXDbLocalizer<TranslateContext, MyMemoryTranslateService>(ops =>
            {
                ops.ResourcesPath = "LocalizationResources";
                ops.AutoAddKeys = true;
                ops.AutoTranslate = true;
                ops.UseExpressMemoryCache = true;
            });`

This doesn't happen if culture is set to the second language, but only if I use the default one.
When I use 'en' for example it works great, it adds a key if missing if not it just loads from the cache.

My sense is telling me that XLocalizer shouldn't even request for a translation if it is in default language but for some reason it does.

Best,
Vito

**Comment by LazZiya** [comment]
Hi Vito,

Glad for knowing that this library is helping you, and thanks for opening this issue. 

You are right, if we are in the source translation culture, or default culture it should not try to translate or cache the key. I will fix this to bypass translation and caching if we are in the same culture as the [`XLocalizerOptions.TranslateFromCulture`](https://github.com/LazZiya/XLocalizer/blob/278f8adad84c5dc6d587cbc5cb137c9fbf4eb01a/XLocalizer/XLocalizerOptions.cs#L45) value.

Kind regards,
Ziya

**Comment by LazZiya** [comment]
Fixed with 29e0a55, and available in [v1.0.1](https://www.nuget.org/packages/XLocalizer.DB/1.0.1)
